### ISSUE TITLE
Linien Style anpassen

### ISSUE THREAD

**Issue by svendroid** [MunichWays/munich-ways-app#17]
- [x] Radlnetz: durchgezogene Linie
- [x] Gesamtnetz: gestrichelte Linie
- [x] Wo kann der Nutzer erkenn was die Linienstyles bedeuten? Legende oder Radnetzauswahl Beschreibung anpassen?

**Comment by svendroid** [comment]
![grafik](https://user-images.githubusercontent.com/1040402/95903954-22ccc500-0d97-11eb-8164-d33c11196076.png)

Ich hab die Linien ein bisschen dünner gemacht und das Strichpattern angepasst.
Was hälst Du davon @thomas-munichways ?

**Comment by thomas-munichways** [comment]
sieht toll aus!

LG, Thomas


Am 13.10.2020 um 21:02 schrieb Sven:
