### ISSUE TITLE
Detailansicht zusätzliche Felder

### ISSUE THREAD

**Issue by thomas-munichways** [MunichWays/munich-ways-app#25]
### Ist: 
- Name
- Strecke
- Ist-Zustand
- Soll-Zustand
- Kategorie
- Link

### Wunsch (wie Carto):
- **Straßenansicht** klick mich! (Feld Bild, ggf. nur als Text mit Mapillary-Link. ggf. ohne "klick mich" weil in der App intuitiv erkennbar)
- Name
- Strecke
- IST - Situation
- Happy Bike Level (1. Streichkandidat, falls es zu viel wird)
- SOLL - Maßnahmen
- Maßnahmen-Kategorie
- Beschreibung (2. Streichkandidat, falls es zu viel wird)
- **munichways_id**
- **Status-Umsetzung**
- **Bezirk** (Feld BA)
- Links

**Comment by svendroid** [comment]
Bzgl. Straßenansicht:
Im geojson sieht ein bild Parameter so aus:
`<a href=\"https://www.mapillary.com/map/im/P7IkXXG1E6K01H7C6BQAjI\" target=\"_blank\">\n<img src=\"https://www.munichways.com/img/Standard_Mapillary.jpg\" width=175></a>`
Als Bild wird häufig ein Standardbild oder der Odeonsplatz angezeigt, z.B. auch in Gräfelfing. Ist das beabsichtigt oder habe ich nur schlecht Beispiele rausgesucht?

Hier könnte ich automatisiert das passend Bild für die geklickte Position über Mapillary API abfragen. Siehe:
https://www.mapillary.com/developer/api-documentation/#images
https://www.mapillary.com/developerpolicy
Problem ist natürlich dass eine Strasse mehrere Bilder hat. Entweder nimmt man immer das Ende oder Anfang, oder wie beschrieben, dynamisch das Bild von der Position wo geklickt wurde. Allerdings ist das evtl. wenig intuitiv wenn es sich immer ändert.

Bzw. ist im `href`-Attribut meist schon die img id enthalten: `P7IkXXG1E6K01H7C6BQAjI`. Dann könnte ich ggf. auch diese nehmen. Allerdings ist es ja auch gewaltig aufwand für jede Strasse per Hand eine id einzupflegen, evtl. wäre hier der Abfrageansatz von oben einfacher.

**Comment by thomas-munichways** [comment]
Hallo Sven,

wir haben für viele Straßen genau den Mapillary-Link herausgesucht, den 
wir zeigen wollen. Das sind alle mit dem Standardbild 
|Standard_Mapillary.jpg. Bei sehr wenigen haben wir den Aufwand 
betrieben auch noch das passende Bild auf unseren Webserver hochzuladen. 
Alle mit dem Bild Offen_Odeonsplatz.jpg haben einfach diesen 
Default-Link zum Odeonsplatz, damit man wenigstens zu Mapillary wechseln 
kann.|

|90 % des Nutzens wäre schon gegeben, wenn einfach genau das Bild und 
der Mapillary-Link wie im geojson / in der Masterliste angegeben ist.
|

|Ideal wäre:
- A: Wenn ein anderes Bild als Standard_Mapillary.jpg oder 
|||Offen_Odeonsplatz.jpg eingetragen ist, |||||dann zeige genau diesen 
Mapillary-Link und dieses Bild an. (nice to have, den Aufwand werden wir 
in Zukunft nicht mehr treiben)
|||

|||||- B: Wenn Standard_Mapillary.jpg eingetragen ist, dann zeige genau 
diesen Mapillary-Link und das entsprechende Bild des Links aus Mapillary.|

||- C: Wenn ||||||Offen_Odeonsplatz.jpg|| eingetragen ist, dann zeige 
irgendeinen Mapillary Link in der nähe an und das |||||entsprechende 
Bild des Links aus Mapillary| (oder das default Bild Odeonsplatz zur 
Unterscheidung von Fall B.)||

||Liebe Grüße
Thomas||

Am 01.11.2020 um 18:29 schrieb Sven:

**Comment by svendroid** [comment]
Straßenansicht fehlt noch. Da das eine größere Aufgabe ist, habe ich es in ein seperates Ticke gelegt. siehe #36
