### ISSUE TITLE
Info / Legende ins Hauptmenü verschieben

### ISSUE THREAD

**Issue by thomas-munichways** [MunichWays/munich-ways-app#31]
Die Legende oben rechts soll woanders integriert werden und nicht das "I" als Info-Symbol verwenden, weil schon im Hauptmenü anders verwendet.

Lösung: die "Legende" mit den "i"-Symbol ins Hauptmenü verschieben

----------------
Original Feedback:
Erstes Feedback von iOS Nutzern 👍 

Stephan Bartling, [30.11.20 16:20]

1. Zwei Info i mit unterschiedlichen Bedeutungen. Die Legende hatte ich rechts oben erst nicht gefunden. Kann man ein passendes Icon evtl. Auf der Karte schweben lassen?
2. Wenn das MunichWays Fremde anschauen, können die die Netze auseinanderhalten? Was bedeutet das für sie/mich als Radler?
- Wenn das dann gut raus kommt, ist das eine wunderbare App wenn man sich in der Stadt mit dem Radl orientieren will!
- Sie ist wie Google. Einfach, aufgeräumt, nicht überladen!

2. erledigt mit #34

**Comment by thomas-munichways** [comment]
Vielleicht können wir im Pop-Up Fenster "Fahrradnetz auswählen" den Link zur Erläuterung auf unserer Homepage anzeigen:
https://www.munichways.com/radlnetz-definitionen/ 

Wir könnten die Texte auf dieser Seite für die App noch anpassen.

**Comment by svendroid** [comment]
zu 1: fällt mir ehrlich gesagt gerade kein passenderes Icon als das i Symbol ein. Aber ich könnte es natürlich auf die Karte ziehen. Alternativ könnte ich mir auch vorstellen die Legenden Info mit in dem Fahrradnetz auswählen Dialog anzuzeigen.

zu 2: Ich fände es glaub ich gut wenn wir die Infos direkt in der App anzeigen, ein Link ist dann doch immer recht viel Aufwand.
Alpenvereinaktiv hat es z.B. so gelöst, dass es einen Info Button direkt an der Auswahl gibt und dieser öffnet eine Info fenster mit allen Infos.
![grafik](https://user-images.githubusercontent.com/1040402/100647594-0f25ef80-3340-11eb-82ba-c1951764b2d6.png) 

Oder wenn die Info sehr kurz ist könnte man es auch direkt unter die Auswahl schreiben.

Was wären denn die korrekten Beschreibungen?
* RadlVorrang-Netz App = RadlVorrang-Strecken MunichWays Website?
* Gesamtnetz App = Rad-Gesamtnetz Webseite?

oder sollten wir die Titel in der App an die Webseite anpassen?

**Comment by thomas-munichways** [comment]
zu 1: zusammen mit Fahrradnetz fände ich besser, dann wird weniger Fläche von der Karte mit Icons bedeckt.
ich hab auch nur ein änlichen Icon wie das für Fahrradnetz gefunden, insoweit würde die Legende dort gut passen.

zu 2: 

- RadlVorrang-Netz App = umbenennen in  "Rad-Vorrangnetz" = Radentscheid München Ziel 2. Es basiert auf den ausgeschilderten Radwegen und wird gemäß den Zielen des Radentscheides entsprechend aktualisiert und erweitert.  

- Gesamtnetz App = Zum Gesamtnetz gehören alle Straßen und Wege, auf denen man mit dem Rad fahren kann.

**Comment by svendroid** [comment]
Punkt 2 wurde in #34 umgesetzt.
Punkt 1 ist noch offen

**Comment by thomas-munichways** [comment]
not needed any more

**Comment by thomas-munichways** [comment]
not needed any more
