### ISSUE TITLE
Unterschiedliche Farben Legende vs Route

### ISSUE THREAD

**Issue by svendroid** [MunichWays/munich-ways-app#32]
Legende - gelb
Karte - orange

**Comment by thomas-munichways** [comment]
Ja gelb war mal schlecht erkennbar, deshalb hatten wir es dunkler gemacht und es wurde orange.
Gelb auf der Karte wäre korrekt.

**Comment by svendroid** [comment]
Hab die Farben mal analog zur Carto Karte gesetzt.
