### ISSUE TITLE
Icon iOS

### ISSUE THREAD

**Issue by thomas-munichways** [MunichWays/munich-ways-app#33]
Stephan Bartling:

Das Icon könnte/sollte größer sein und hat auch ein Kreuz im Hintergrund. Absicht?

Vielleicht haben wir das Falsche Logo für facebook und Instagram erwischt, das hat größere Ränder.
![MunichWays_Logo_rund_FB](https://user-images.githubusercontent.com/46649582/100650715-a2612400-3344-11eb-818f-081928af1b67.png)

**Comment by svendroid** [comment]
Das Kreuz im Hintergrund ist ein Fehler, hab vergessen die Hilfslinien beim Export auszublenden.
Ich habs mal ein bisschen größer gemacht, aber sonst werden die Ränder glaub ich zu klein:
![grafik](https://user-images.githubusercontent.com/1040402/100652523-56fc4500-3347-11eb-91fc-46bf0d5b202e.png)

So besser?
