### ISSUE TITLE
Gesamtnetz umbenennen in Alle Strecken

### ISSUE THREAD

**Issue by thomas-munichways** [MunichWays/munich-ways-app#34]
Gemäß unserer neuen Sprachregelung der verschiedenen Netze:
https://www.munichways.com/radlnetz-definitionen/ 

### Tasks
* Gesamtnetz umbenennen in "Alle Strecken" (als kurzform zu "Anbindung alle Strecken")

**Comment by svendroid** [comment]
Ist das dass gleiche wie in #31 ?
Dann hätte wir im Dialog zur Netzauswahl:

- Fahrradnetz auswählen:
    - Option1: Rad-Vorrangnetz
        - Beschreibung: Radentscheid München Ziel 2. Es basiert auf den ausgeschilderten Radwegen und wird gemäß den Zielen des Radentscheides entsprechend aktualisiert und erweitert.
    - Option2: Alle Strecken
        - Beschreibung: Zum Gesamtnetz gehören alle Straßen und Wege, auf denen man mit dem Rad fahren kann.

Bei Option2 in der Beschreibung wird noch Gesamtznetz verwendet. Durch "alle Straßen und Wege, auf denen man mit dem Rad fahren kann." ersetzen?

**Comment by thomas-munichways** [comment]
Ja #31 Punkt 2 und #34 sind das gleiche. Wir haben jetzt auch die Beschreibungen auf der Homepage aktulisiert, das können wir übernehmen.

* Option 1: RadlVorrang-Netz
  * Radentscheid München Ziel 2. Es basiert auf den ausgeschilderten Radwegen und wird gemäß den Zielen des Radentscheides entsprechend aktualisiert und erweitert.
* Option 2: Anbindung alle Strecken
  * Alle Straßen und Wege, auf denen man mit dem Rad fahren kann.

Dann ist es einheitlich,  Webseite/Carto/QGIS/App
Den 2. Satz bei Option 1 könnten wir auch weglassen, wenn es zu lang wird.

**Comment by svendroid** [comment]
![grafik](https://user-images.githubusercontent.com/1040402/104844101-6cfd9f00-58ce-11eb-8f8c-e4d81712357b.png)

Titel umbenannt und Beschreibungen hinzugefügt.
