### ISSUE TITLE
Datenverbrauch verbesseren

### ISSUE THREAD

**Issue by svendroid** [MunichWays/munich-ways-app#37]
Das Radlvorrangnetz ist mittlerweile ziemlich groß: 5.6 MB
Diese werden bei jedem Start erneut heruntergeladen.

Das dauert lange und ist auch Datenverschwendung.

Wie können wir das verbesseren?
- unnötige Infos aus dem geojson entfernen?
- Daten cachen und nur jede Woche herunteladen?

Erforderlich Felder:
siehe [https://github.com/MunichWays/Carto/wiki/Feldbeschreibung-dataset](https://github.com/MunichWays/Carto/wiki/Feldbeschreibung-dataset)

1. Entwurf, zu prüfen:
radlvorrangnetz_app_V03.geojson (mittlerweile haben wir schon V04)
relevante Felder für die App aus radlvorrangnetz_masterliste plus Geom aus radlvorrangnetz

rv.cartodb_id, rv.the_geom ~~, rvm.strassenansicht_klick_mich~~ , rvm.name, rvm.strecke, rvm.ist_situation, rvm.happy_bike_level, rvm.soll_massnahmen, rvm.massnahmen_kategorie_link, rvm.beschreibung, rvm.munichways_id ~~, rvm.status_umsetzung~~ ~~, rvm.bezirk_link~~, rvm.links , rvm.netztyp ~~, rvm.plan_netztyp_id~~ , rvm.farbe ~~, rvm.rsv_strecke~~ ~~, rvm.alternative~~ ~~, rvm.viel_Kfz~~ ~~, rvm.bild~~ ~~, rvm.mapillary_link~~ , Mapillary_Img_ID ~~, rvm.bezirk_region~~ , rvm.bezirk_nummer, rvm.bezirk_name , rvm.massnahmen_kategorie ~~, rvm.Prio_Gesamt~~ ~~, rvm.Neuralgischer_Punkt~~ ~~, rvm.kategorie_id~~ ~~, rvm.status_id~~ , rvm.netztyp_id ~~, rvm.rsv_boolean~~, now() last_updated

**Comment by svendroid** [comment]
Hi @thomas-munichways,
wenn ich nix übersehen habe werden aktuell folgende Felder in der App verwendet:

```
rv.cartodb_id, rv.the_geom, rvm.name, rvm.strecke, rvm.ist_situation, rvm.happy_bike_level, rvm.soll_massnahmen, rvm.massnahmen_kategorie_link, rvm.beschreibung, rvm.munichways_id, rvm.status_umsetzung, rvm.links, rvm.farbe, mapillary_img_id, rvm.bezirk_nummer, rvm.bezirk_name, rvm.netztyp_id, last_updated
```
Im Vergleich zu oben gab es folgende Änderungen:

löschen: rvm.netztyp, rvm.massnahmen_kategorie
hinzufügen: rvm.status_umsetzung

**Comment by thomas-munichways** [comment]
Hi @svendroid ,

die Uploads stehen bereit. Die neue abgespeckte Version radlvorrangnetz_app_V03.geojson ist 2 MB kleiner.

Wir können dann bald die Betaversion 0.0.8(10) freigeben oder überspringen?

Liebe Grüße
Thomas

**Comment by svendroid** [comment]
@thomas-munichways , mir ist gerade noch aufgefallen, dass man auch die grauen, also geplanten, Strecken rausfiltern könnte, da diese in der App nicht angezeigt werden.

**Comment by thomas-munichways** [comment]
gute Idee, hab ich in der Abfrage ergänzt. where farbe <> 'grau'
