### ISSUE TITLE
Bildschirmsperre ausschalten

### ISSUE THREAD

**Issue by thomas-munichways** [MunichWays/munich-ways-app#39]
Feedback von Alexander Pichler

ich möchte als User nicht immer meinen Code eingeben müssen, wenn ich den Bildschirm wieder einschalte.
Das ist auf dem Fahrrad sehr schwierig und während der Fahrt gefährlich.

Bei Koomot ist es so gelöst, dass die App fragt, ob sie die Geräteeinstellungen ändern darf. 

- Bildschirm kann ohne Entsperrung (Muster, PIN, Fingerabdruck) wieder angeschaltet werden solange die App läuft.

**Comment by svendroid** [comment]
Ich hab es jetzt wie folgt umgesetzt:
1. nur Android: Wenn die App an ist und der Bildschirm gesperrt wird, muss man beim Anschalten der App den PIN nicht eingeben. Die erneute PIN Eingabe wird erst notwendig wenn man den Screen verlässt.
2. iOS & Android: Wenn der "Anpeilmodus" auf ein Ziel (also der blaue Pfeil wird anzeigt) aktiv ist, bleibt der Bildschirm an & wird nicht von alleine ausgeschaltet. Manuell kann man das natürlich machen.
