### ISSUE TITLE
Suchfeld

### ISSUE THREAD

**Issue by svendroid** [MunichWays/munich-ways-app#5]
User Story: unbekanntes Ziel finden
 
- Ich als User möchte mit dem Rad zu einer Verabredung in ein Restaurant in Schwabing. Ich kenne die Adresse aber in diesem Viertel kenne ich mich aber nicht aus.
- Ich möchte das Ziel finden und als Zielort sehen.
- Dann fahre ich los, in meinem Viertel kenne ich mich noch aus. Ab Stadtmitte orientiere ich mich an den Farben der Strecken in der App. In Schwabing orientiere ich mich am Zielort.
 
## Tasks
-  eine Lupe als Suchsymbol anzeigen. 
- Wenn man es anklickt erscheint ein Eingabefeld.
- Ich gebe das Ziel in das Suchfeld ein und wähle die Zieladresse aus / klicke auf ein Suchergebnis. 
-  das Suchergebnis wird in der Karte angezeigt, z.B. wie bei Google Maps als Fahne 
![image](https://user-images.githubusercontent.com/46649582/95648271-2bdb3f00-0ad6-11eb-9504-94d6da4a03ed.png)

- Der Focus fliegt zum Suchergebnis.

## Out of Scope
- Ziel anvisieren --> issue #16

## Offen
- Wie kann man dann den Zielort löschen? Vielleicht indem man den Text im Suchfeld löscht, indem man rechts am Suchfeld auf das Kreuz klickt.

**Comment by thomas-munichways** [comment]
original siehe https://github.com/AppWerft/MunichWays/issues/6

**Comment by svendroid** [comment]
Ich hab mir mal eine erste Skizze gemacht, wie man es vom Ablauf her umsetzen könnte:

![grafik](https://user-images.githubusercontent.com/1040402/116809600-1182b480-ab3f-11eb-9f44-20037ac08094.png)

**Comment by thomas-munichways** [comment]
schaut schon gut aus. Das Symbol der Markierung sieht unvollständig aus, fehlt da eine Umrandung und ein punkt in der Mitte in schwarz oder in weiß?

Was passiert, wenn man das Feld unten mit dem Kreuz schließt? ist die Markierung dann noch da?
Wie kann man die Markierung wieder löschen?

**Comment by svendroid** [comment]
Der aktuelle Stand sieht wie folgt aus:

https://user-images.githubusercontent.com/1040402/121389413-ace02400-c94c-11eb-9bf7-58eb7da984ba.mp4

Man kann nach einem Ziel suchen, wenn dieses ausgewählt wird, wird es auf der Karte dargestellt, und ein Pfeil in der Mitte vom Bildschirm angezeigt der immer in die Richtung von dem Ziel zeigt, wenn man erneut auf den Suchbutton klickt wird das Ziel wieder ausgeblendet.

Offene Punkte:
- Löschfunktion eventuell anders umsetzen? eventuell extra Button spendieren und einen weiteren button zeigen der das zentrieren des Ziels erlaubt?
- Icons von Pfeil und Pin anpassen?

Was meinst Du @thomas-munichways ? Kommt das an Deine Idee ran?

**Comment by thomas-munichways** [comment]
Hi Sven,

sieht super aus. Ich denke so brauchen wir keinen extra Button zum Löschen des Ziels.
Ich verstehe es so, dass man weiterhin auf die eigene Position zentrieren kann. Ein weiter entferntes Ziel ist dann evtl. nicht mehr im Bild, richtig?

Liebe Grüße
Thomas



________________________________
Von: Sven ***@***.***>
Gesendet: Mittwoch, 9. Juni 2021 18:05
An: MunichWays/munich-ways-app ***@***.***>
Cc: Thomas Häusler ***@***.***>; Mention ***@***.***>
Betreff: Re: [MunichWays/munich-ways-app] Suchfeld (#5)


Der aktuelle Stand sieht wie folgt aus:

https://user-images.githubusercontent.com/1040402/121389413-ace02400-c94c-11eb-9bf7-58eb7da984ba.mp4

Man kann nach einem Ziel suchen, wenn dieses ausgewählt wird, wird es auf der Karte dargestellt, und ein Pfeil in der Mitte vom Bildschirm angezeigt der immer in die Richtung von dem Ziel zeigt, wenn man erneut auf den Suchbutton klickt wird das Ziel wieder ausgeblendet.

Offene Punkte:

  *   Löschfunktion eventuell anders umsetzen? eventuell extra Button spendieren und einen weiteren button zeigen der das zentrieren des Ziels erlaubt?
  *   Icons von Pfeil und Pin anpassen?

Was meinst Du @thomas-munichways<https://github.com/thomas-munichways> ? Kommt das an Deine Idee ran?

**Comment by svendroid** [comment]
Ja man kann weiterhin auf die eigene Position zentrieren. Der Pfeil, der auf das Ziel zeigt, ist dann unter der aktuellen Positionsanzeige und dadurch hat man dann weiterhin einen Indikator wo sich das Ziel befindet, auch wenn man weiter entfernt ist.
