### ISSUE TITLE
Sucheergebnisse merken

### ISSUE THREAD

**Issue by thomas-munichways** [MunichWays/munich-ways-app#50]
Wenn ich auf die Suche klicke, werden im Suchfeld die zuletzt verwendeten Suchergebnisse zur Auswahl angezeigt.

**Comment by uvelogs** [comment]
Entwurf für die Anzeige eines Suchverlauf.

![search](https://github.com/MunichWays/munich-ways-app/assets/119749124/fac154af-b910-431e-8948-4364afbe655c)

**Comment by thomas-munichways** [comment]
Wenn es nur lokal im Handy vorhalten, brauchen wir keine Nutzerdaten speichern
