### ISSUE TITLE
Karte neu Laden prominenter anbieten

### ISSUE THREAD

**Issue by thomas-munichways** [MunichWays/munich-ways-app#56]
### Problem
Die Kate wird wöchentlich im FTP-Verzeichnis aktualisiert. Neuerungen und Fehlerkorrekturen werden in der App erst sichtbar, wenn die Karte neu geladen wird. Das passiert nicht automatisch bei jedem Start.
Man kann unter dem Menü Info "Radlnetz löschen" klicken. Das ist nach Feedback mehrerer die Anwender*innen  aus 2 Gründen etwas unklar.
1. Unter "Info" wird so eine Funktion nicht erwartet
2. Der Titel "Radnetz löschen" schreckt manche ab

### Lösung

1. Funktion verschieben als 3. Hauptpunkt im Menü oder als einzigr Funktion unter einem neuen 3. Hauptmenüpung "Einstellungen"
2. Umbenennen von "Radnetz löschen" in "Radnetz neu laden"

**Comment by svendroid** [comment]
Hab es wie vorgeschlagen umgesetzt und in die Einstellungen verschoben. Der aktuelle Cache läuft nach einer Woche aus, den könnte ich natürlich anpassen, so dass er z.B. jeden Tag oder alle 3 Tage die Daten neu abfrägt
