### ISSUE TITLE
Sichtbarkeit Positionsanzeige verbessern

### ISSUE THREAD

**Issue by svendroid** [MunichWays/munich-ways-app#6]
> Die eigene position ist beim fahren mit dem dezenten blauen Punkt nicht gut zu erkennen.
>In der App Bayernnetz für Radler wird ein roter Pfeil verwendet, der immer noch dezent klein ist aber deutlich besser sichtbar.

siehe https://github.com/AppWerft/MunichWays/issues/22

**Comment by thomas-munichways** [comment]
Der blaue Punkt ist bereits größer und jetzt gut sichtbar. Dieses Issue können wir schließen.
