### ISSUE TITLE
Update auf Android 13 (API-Level 33)

### ISSUE THREAD

**Issue by thomas-munichways** [MunichWays/munich-ways-app#79]
Probleme beheben
Dein höchstes Ziel-API-Level ist Android 12 (API-Level 31).

Aktualisiere deine App auf Android 13 (API-Level 33).

[stackoverflow.com: how-to-upgrade-targetsdkversion-33](https://stackoverflow.com/questions/74697203/how-to-upgrade-targetsdkversion-33)

open android folder > app folder > **build.gradle**
targetSdkVersion 31 --> targetSdkVersion 33
oder

- replace compileSdkVersion flutter.compileSdkVersion with Math.max(flutter.compileSdkVersion, 33)
- replace targetSdkVersion flutter.targetSdkVersion with targetSdkVersion Math.max(flutter.targetSdkVersion, 33)
- replace minSdkVersion flutter.minSdkVersion with minSdkVersion Math.max(flutter.minSdkVersion, 23) if required.

**Comment by svendroid** [comment]
Ich hab das Android Level auf 33 angehoben. Test auf Gerät mit Android 33 funktioniert. Ich release das gleich in Google Play.

Langfristig könnten wir auch die Flutter Version an sich anheben, aber das ist nicht super dringend.
