### ISSUE TITLE
Absturz beim Zoom Out nach Implementierung der Mapillary API v4.

### ISSUE THREAD

**Issue by uvelogs** [MunichWays/munich-ways-app#85]
Beim Herauszoomen stürzt die App in der Nähe des Zoom Level 12 ab.

Vermutung: Implemetierung des FutureBuilder in der Detailansicht.

Ursache: SaveLayers: true in ClickablePolyLine Aufruf. Wurde von mir fälschlicherweise eingefügt.

Lösung: 
1. Zeile löschen in ClickablePolyLine (map_screen.dart)
2. Refactoring: FutureBuilder innerhalb der ListView einbinden und ein _MapillaryImage Widget zurückliefern, wenn Thumbnail geladen wurde. Während des Ladevorganges ein CircularProgressIndicator anzeigen.

**Comment by svendroid** [comment]
Hab den Crash auf Produkation in 1.2.1 nachvollziehen können und nach deinem Fix tritt er bei mir nicht mehr auf. Ich release das gleich in Google Play und schließe den Bug hier.
